// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SatParameters.proto

#ifndef PROTOBUF_SatParameters_2eproto__INCLUDED
#define PROTOBUF_SatParameters_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_SatParameters_2eproto();
void protobuf_AssignDesc_SatParameters_2eproto();
void protobuf_ShutdownFile_SatParameters_2eproto();

class SatParameters;

enum SatParameters_VariableOrder {
  SatParameters_VariableOrder_IN_ORDER = 0,
  SatParameters_VariableOrder_IN_REVERSER_ORDER = 1,
  SatParameters_VariableOrder_IN_RANDOM_ORDER = 2
};
bool SatParameters_VariableOrder_IsValid(int value);
const SatParameters_VariableOrder SatParameters_VariableOrder_VariableOrder_MIN = SatParameters_VariableOrder_IN_ORDER;
const SatParameters_VariableOrder SatParameters_VariableOrder_VariableOrder_MAX = SatParameters_VariableOrder_IN_RANDOM_ORDER;
const int SatParameters_VariableOrder_VariableOrder_ARRAYSIZE = SatParameters_VariableOrder_VariableOrder_MAX + 1;

const ::google::protobuf::EnumDescriptor* SatParameters_VariableOrder_descriptor();
inline const ::std::string& SatParameters_VariableOrder_Name(SatParameters_VariableOrder value) {
  return ::google::protobuf::internal::NameOfEnum(
    SatParameters_VariableOrder_descriptor(), value);
}
inline bool SatParameters_VariableOrder_Parse(
    const ::std::string& name, SatParameters_VariableOrder* value) {
  return ::google::protobuf::internal::ParseNamedEnum<SatParameters_VariableOrder>(
    SatParameters_VariableOrder_descriptor(), name, value);
}
// ===================================================================

class SatParameters : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:SatParameters) */ {
 public:
  SatParameters();
  virtual ~SatParameters();

  SatParameters(const SatParameters& from);

  inline SatParameters& operator=(const SatParameters& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SatParameters& default_instance();

  void Swap(SatParameters* other);

  // implements Message ----------------------------------------------

  inline SatParameters* New() const { return New(NULL); }

  SatParameters* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SatParameters& from);
  void MergeFrom(const SatParameters& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SatParameters* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef SatParameters_VariableOrder VariableOrder;
  static const VariableOrder IN_ORDER =
    SatParameters_VariableOrder_IN_ORDER;
  static const VariableOrder IN_REVERSER_ORDER =
    SatParameters_VariableOrder_IN_REVERSER_ORDER;
  static const VariableOrder IN_RANDOM_ORDER =
    SatParameters_VariableOrder_IN_RANDOM_ORDER;
  static inline bool VariableOrder_IsValid(int value) {
    return SatParameters_VariableOrder_IsValid(value);
  }
  static const VariableOrder VariableOrder_MIN =
    SatParameters_VariableOrder_VariableOrder_MIN;
  static const VariableOrder VariableOrder_MAX =
    SatParameters_VariableOrder_VariableOrder_MAX;
  static const int VariableOrder_ARRAYSIZE =
    SatParameters_VariableOrder_VariableOrder_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  VariableOrder_descriptor() {
    return SatParameters_VariableOrder_descriptor();
  }
  static inline const ::std::string& VariableOrder_Name(VariableOrder value) {
    return SatParameters_VariableOrder_Name(value);
  }
  static inline bool VariableOrder_Parse(const ::std::string& name,
      VariableOrder* value) {
    return SatParameters_VariableOrder_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional .SatParameters.VariableOrder preferred_variable_order = 1 [default = IN_ORDER];
  bool has_preferred_variable_order() const;
  void clear_preferred_variable_order();
  static const int kPreferredVariableOrderFieldNumber = 1;
  ::SatParameters_VariableOrder preferred_variable_order() const;
  void set_preferred_variable_order(::SatParameters_VariableOrder value);

  // @@protoc_insertion_point(class_scope:SatParameters)
 private:
  inline void set_has_preferred_variable_order();
  inline void clear_has_preferred_variable_order();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  int preferred_variable_order_;
  friend void  protobuf_AddDesc_SatParameters_2eproto();
  friend void protobuf_AssignDesc_SatParameters_2eproto();
  friend void protobuf_ShutdownFile_SatParameters_2eproto();

  void InitAsDefaultInstance();
  static SatParameters* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// SatParameters

// optional .SatParameters.VariableOrder preferred_variable_order = 1 [default = IN_ORDER];
inline bool SatParameters::has_preferred_variable_order() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SatParameters::set_has_preferred_variable_order() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SatParameters::clear_has_preferred_variable_order() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SatParameters::clear_preferred_variable_order() {
  preferred_variable_order_ = 0;
  clear_has_preferred_variable_order();
}
inline ::SatParameters_VariableOrder SatParameters::preferred_variable_order() const {
  // @@protoc_insertion_point(field_get:SatParameters.preferred_variable_order)
  return static_cast< ::SatParameters_VariableOrder >(preferred_variable_order_);
}
inline void SatParameters::set_preferred_variable_order(::SatParameters_VariableOrder value) {
  assert(::SatParameters_VariableOrder_IsValid(value));
  set_has_preferred_variable_order();
  preferred_variable_order_ = value;
  // @@protoc_insertion_point(field_set:SatParameters.preferred_variable_order)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::SatParameters_VariableOrder> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::SatParameters_VariableOrder>() {
  return ::SatParameters_VariableOrder_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_SatParameters_2eproto__INCLUDED
