// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SatParameters.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "SatParameters.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* SatParameters_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SatParameters_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* SatParameters_VariableOrder_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_SatParameters_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_SatParameters_2eproto() {
  protobuf_AddDesc_SatParameters_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "SatParameters.proto");
  GOOGLE_CHECK(file != NULL);
  SatParameters_descriptor_ = file->message_type(0);
  static const int SatParameters_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SatParameters, preferred_variable_order_),
  };
  SatParameters_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      SatParameters_descriptor_,
      SatParameters::default_instance_,
      SatParameters_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SatParameters, _has_bits_[0]),
      -1,
      -1,
      sizeof(SatParameters),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SatParameters, _internal_metadata_),
      -1);
  SatParameters_VariableOrder_descriptor_ = SatParameters_descriptor_->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_SatParameters_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      SatParameters_descriptor_, &SatParameters::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_SatParameters_2eproto() {
  delete SatParameters::default_instance_;
  delete SatParameters_reflection_;
}

void protobuf_AddDesc_SatParameters_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_SatParameters_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\023SatParameters.proto\"\244\001\n\rSatParameters\022"
    "H\n\030preferred_variable_order\030\001 \001(\0162\034.SatP"
    "arameters.VariableOrder:\010IN_ORDER\"I\n\rVar"
    "iableOrder\022\014\n\010IN_ORDER\020\000\022\025\n\021IN_REVERSER_"
    "ORDER\020\001\022\023\n\017IN_RANDOM_ORDER\020\002", 188);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "SatParameters.proto", &protobuf_RegisterTypes);
  SatParameters::default_instance_ = new SatParameters();
  SatParameters::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_SatParameters_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_SatParameters_2eproto {
  StaticDescriptorInitializer_SatParameters_2eproto() {
    protobuf_AddDesc_SatParameters_2eproto();
  }
} static_descriptor_initializer_SatParameters_2eproto_;

// ===================================================================

const ::google::protobuf::EnumDescriptor* SatParameters_VariableOrder_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SatParameters_VariableOrder_descriptor_;
}
bool SatParameters_VariableOrder_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const SatParameters_VariableOrder SatParameters::IN_ORDER;
const SatParameters_VariableOrder SatParameters::IN_REVERSER_ORDER;
const SatParameters_VariableOrder SatParameters::IN_RANDOM_ORDER;
const SatParameters_VariableOrder SatParameters::VariableOrder_MIN;
const SatParameters_VariableOrder SatParameters::VariableOrder_MAX;
const int SatParameters::VariableOrder_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SatParameters::kPreferredVariableOrderFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SatParameters::SatParameters()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:SatParameters)
}

void SatParameters::InitAsDefaultInstance() {
}

SatParameters::SatParameters(const SatParameters& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:SatParameters)
}

void SatParameters::SharedCtor() {
  _cached_size_ = 0;
  preferred_variable_order_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SatParameters::~SatParameters() {
  // @@protoc_insertion_point(destructor:SatParameters)
  SharedDtor();
}

void SatParameters::SharedDtor() {
  if (this != default_instance_) {
  }
}

void SatParameters::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SatParameters::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SatParameters_descriptor_;
}

const SatParameters& SatParameters::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_SatParameters_2eproto();
  return *default_instance_;
}

SatParameters* SatParameters::default_instance_ = NULL;

SatParameters* SatParameters::New(::google::protobuf::Arena* arena) const {
  SatParameters* n = new SatParameters;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void SatParameters::Clear() {
// @@protoc_insertion_point(message_clear_start:SatParameters)
  preferred_variable_order_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool SatParameters::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:SatParameters)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .SatParameters.VariableOrder preferred_variable_order = 1 [default = IN_ORDER];
      case 1: {
        if (tag == 8) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::SatParameters_VariableOrder_IsValid(value)) {
            set_preferred_variable_order(static_cast< ::SatParameters_VariableOrder >(value));
          } else {
            mutable_unknown_fields()->AddVarint(1, value);
          }
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:SatParameters)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:SatParameters)
  return false;
#undef DO_
}

void SatParameters::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:SatParameters)
  // optional .SatParameters.VariableOrder preferred_variable_order = 1 [default = IN_ORDER];
  if (has_preferred_variable_order()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->preferred_variable_order(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:SatParameters)
}

::google::protobuf::uint8* SatParameters::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:SatParameters)
  // optional .SatParameters.VariableOrder preferred_variable_order = 1 [default = IN_ORDER];
  if (has_preferred_variable_order()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->preferred_variable_order(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:SatParameters)
  return target;
}

int SatParameters::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:SatParameters)
  int total_size = 0;

  // optional .SatParameters.VariableOrder preferred_variable_order = 1 [default = IN_ORDER];
  if (has_preferred_variable_order()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->preferred_variable_order());
  }

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SatParameters::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:SatParameters)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const SatParameters* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const SatParameters>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:SatParameters)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:SatParameters)
    MergeFrom(*source);
  }
}

void SatParameters::MergeFrom(const SatParameters& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:SatParameters)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_preferred_variable_order()) {
      set_preferred_variable_order(from.preferred_variable_order());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void SatParameters::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:SatParameters)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SatParameters::CopyFrom(const SatParameters& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:SatParameters)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SatParameters::IsInitialized() const {

  return true;
}

void SatParameters::Swap(SatParameters* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SatParameters::InternalSwap(SatParameters* other) {
  std::swap(preferred_variable_order_, other->preferred_variable_order_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata SatParameters::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SatParameters_descriptor_;
  metadata.reflection = SatParameters_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// SatParameters

// optional .SatParameters.VariableOrder preferred_variable_order = 1 [default = IN_ORDER];
bool SatParameters::has_preferred_variable_order() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void SatParameters::set_has_preferred_variable_order() {
  _has_bits_[0] |= 0x00000001u;
}
void SatParameters::clear_has_preferred_variable_order() {
  _has_bits_[0] &= ~0x00000001u;
}
void SatParameters::clear_preferred_variable_order() {
  preferred_variable_order_ = 0;
  clear_has_preferred_variable_order();
}
 ::SatParameters_VariableOrder SatParameters::preferred_variable_order() const {
  // @@protoc_insertion_point(field_get:SatParameters.preferred_variable_order)
  return static_cast< ::SatParameters_VariableOrder >(preferred_variable_order_);
}
 void SatParameters::set_preferred_variable_order(::SatParameters_VariableOrder value) {
  assert(::SatParameters_VariableOrder_IsValid(value));
  set_has_preferred_variable_order();
  preferred_variable_order_ = value;
  // @@protoc_insertion_point(field_set:SatParameters.preferred_variable_order)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
